import { type NextPage } from "next";
import { debounce } from "lodash";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [data, setData] = useState(null);
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const callAPI = async (event: any) => {

    console.log("event", event.target.value);
    try {
      const res = await fetch(
        `https://api.artic.edu/api/v1/artworks/search?limit=10&q=${event.target.value}&fields=id,title,artist_title,image_id`,
        {
          method: "GET",
          headers: {
            'AIC-User-Agent': 'Matthew Berger (matthew17berger@gmail.com)'
          }
        }
      );

      const searchResults = await res.json();
      setData(searchResults.data);

      console.log("searchResults");
      console.log(searchResults);
      console.log(event.target.value);

    } catch (err) {
      console.error(err);
    }
  };

  if (!data) {
    callAPI({ target: { value: '' } });
    return
  }

  return (
    <>
      <Head>
        <title>Framer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen px-6 pb-36 pt-6 bg-teal-900">
        <div className="py-2 flex gap-8 items-bottom justify-between">
          <h1 className="text-6xl text-teal-300 font-bold mb-6">Art Search</h1>
          <input
            className="p-3 mb-16 w-80 rounded-md border border-gray-200 bg-teal-800 text-white placeholder:text-gray-200"
            onChange={debounce(callAPI, 200)} type="text" placeholder="Search..."></input>
        </div>

        <div className="grid grid-cols-[repeat(auto-fill,_minmax(300px,_1fr))] gap-8">
          {data.map((item: any) => (
            <Link href={`/${item.id}`} key={item.id}
                  className="flex flex-col bg-white rounded-md shadow-lg overflow-clip">
              <img src={`https://www.artic.edu/iiif/2/${item.image_id}/full/843,/0/default.jpg`} alt={item.title}
                   className="h-64 w-full object-cover" />
              <div className="p-4">
                <h3 className="text-2xl font-bold">{item.title}</h3>
                <h4 className="text-lg">{item.artist_title}</h4>
              </div>
            </Link>
          ))}
        </div>

      </main>
    </>
  );
};

export default Home;
